language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
env:
global:
  - DEPLOY=deploy
services:
  - postgresql

defore_script:
  - "psql -c 'CREATE DATABASE store-manager-main;' -U postgres -P krs1"

after_success:
  - coveralls
script:
 - py.test --cov