language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
env:
  global:
    - export DEPLOYMENT_CONF=Deployment
    - export CONFIG_NAME=deployment
services:
  - postgresql

defore_script:
  - export CONFIG_NAME=deployment
  - "psql -c 'CREATE DATABASE store_manager;' -U postgres"

after_success:
  - coveralls
script:
 - py.test --cov