language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
services:
  - postgresql

defore_script:
  - psql -c 'CREATE DATABASE store-manager-main;' -U postgres

after_success:
  - coveralls
script:
 - py.test --cov
env:
global:
  - DEPLOY=True